services:
  postgres:
    image: postgres:latest
    container_name: dev_postgres
    restart: no
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      # - pg_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

# volumes:
#   pg_data:

